# Site settings

title: Qile Yang's Site
description: >- # this means to ignore newlines until "baseurl:"
  My personal Website
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  Qile0317
google_analytics: G-PT1NQKN626

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-titles-from-headings
  - jekyll-postcss-v2

postcss:
  cache: false

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true
